spring:
  application:    name: config-client-<env> <-- Config server will match any application.yml with the spring.application.name.
  cloud:
    config:
      uri:
      - http://config-server:8888
      discovery:
        enabled: true
