server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - health
        - info
        - beans
        - conditions
        - env
        - config-props
        - mappings
        - loggers
  endpoint:
    health:
      show-details: always
  info:
      git:
        mode: full
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831