server:
  port: 8080
  servlet:
    context-path: /
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:9443/oauth2/jwks
        opaquetoken:
          client-id: KUruvYhjqBVRx2LXbwcnsiGY4iMa
          client-secret: 992NTm1fNTEIQp3QUCtOfr_OCc0a
          introspection-uri: https://localhost:9443/oauth2/introspect
logging:
  level:
    '[org.springframework.security]': debug