server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github/repository
          username: username
          password: password
          search-paths:
          - folder1
          - folder2
          - folder*
          default-label: branch
            
